### ISSUE TITLE
validation seems "broken" with optional or union

### ISSUE THREAD

**Issue by fengzilong** [ianstormtaylor/superstruct#206] opened 2019-12-16 05:40 UTC
Here are some examples

### Correct example

```js
const options = struct.object( {
  entry: 'string',
  title: 'string?'
} )

const schema = struct( {
  options
} )
```

If I use this schema to validate

```json
{
  "options": {}
}
```

everything works well as expected

Output:

```bash
Expected a value of type `string` for `options.entry` but received `undefined`
```

### "Broken" one

But when I use it together with struct.union

```js
const options = struct.object( {
  entry: 'string',
  title: 'string?'
} )

const schema = struct( {
  options: struct.union( [ 'string', options ] )
} )
```

to validate

```json
{
  "options": {}
}
```

output:

```bash
Expected a value of type `string | {entry,title}` for `options` but received `{}`
```

**the error message here is not clear**, because `title` is optional, `entry` is required, `{entry,title}` didn't indicate this information

What I expected is still

```bash
Expected a value of type `string` for `options.entry` but received `undefined`
```

### Environment

**superstruct version:** ^0.8.2
**node version:** 10.16.3

**Comment by fengzilong** [comment] 2019-12-16 06:00
I know maybe in some case there are some similar object-schemas in union

```js
const a = struct.object( {
  key: 'string'
} )

const b = struct.object( {
  differentKey: 'string'
} )

const schema = struct( {
  options: struct.union( a, b )
} )
```

It's difficult to distinguish them, but in most cases contains limited types like `string / object / boolean`, it's simple to identify which schema to use with `typeof`

**Comment by ianstormtaylor** [comment] 2019-12-16 18:57
I think this is a duplicate of https://github.com/ianstormtaylor/superstruct/issues/96, so going to close in favor of that one. Thanks for understanding

**Closed by ianstormtaylor** 2019-12-16 18:57 UTC
