### ISSUE TITLE
`optional` is not inferred as optional field in TypeScript types

### ISSUE THREAD

**Issue by Mrtenz** [ianstormtaylor/superstruct#804] opened 2021-05-21 13:28 UTC
When using `object` with an optional field, that field is not optional in the inferred TypeScript type:

```ts
const TestStruct = object({
  foo: optional(string())
});

type Type = Infer<typeof TestStruct>; // { to: string }
```

I would expect the type to be inferred as `{ to?: string }` instead.

**Comment by EvanLovely** [comment] 2021-06-12 00:59
Do you have `strictNullChecks: true` in your `tsconfig.json`? I know that can throw it off.

**Comment by teneon** [comment] 2021-07-05 21:59
I have encountered the exact same problem as Mrtenz. I am reading documentation / typescript section / Infer. It states the following:

_If you are **not** using TypeScript's strictNullChecks option, Superstruct will be unable to infer your "optional" types correctly and will mark all types as optional._

Am i reading this correctly? The documentation basically states that `strictNullChecks` should be set to `true` if we want **Infer** to work properly in Typescript. I have it set to `true` and i still have the exact same problem as Mrtenz. And basically strictNullChecks should be always set to true in my opinion.

BTW guys... amazing library! If this problem could be solved, it would be awesome ;)

best regards,
Neon

**Comment by teneon** [comment] 2021-07-05 22:31
Actually this only happens, if you use unknown() type. E.g. 
```
  const TestStruct = object({
    foo: optional(string()),
    baz: optional(unknown())
  });

  type Type = Infer<typeof TestStruct>;
```
Both foo and baz should be optional, but if you add the snippet to VSCode, hover mouse over Type, you can see that "foo" is optional, but "baz" is required. Seems like a bug?

best regards,
Neon

**Comment by thesunny** [comment] 2022-04-25 20:31
@ianstormtaylor Hi Ian, sorry for drawing your attention to one issue but I think this one disproportionately affects the usefulness of the library.

It's common to want an optional property, for example for API endpoints, and because optional doesn't work with objects it removes its ability to be used in these use cases. It's possible this used to work and something in TypeScript has changed or something in SuperStruct has changed. SuperStruct is on TypeScript 4.1.2 which is a number of versions behind 4.6.3 which is current.

I have tried a few things:

*   I set `strictNullChecks` to false but it didn't change the outcome
*   I made sure I was on the latest version of TypeScript including modifying vscode settings to use the version in `node_modules` (and reloaded TypeScript)
*   I created a minimal reproduction in a separate project

Here is the code for the minimal reproduction

```typescript
import * as s from "superstruct";

const PropsStruct = s.object({
  age: s.optional(s.number()),
});

type PropsType = s.Infer<typeof PropsStruct>;

// type PropsType = {
//    age: number; <-- should be `age?` and/or `number | undefined`
// }
```

I looked at the source code and I didn't dive into it too deeply, but it does seem that SuperStruct tries to handle this case.

I think the main file of interest is [https://github.com/ianstormtaylor/superstruct/blob/main/src/utils.ts](https://github.com/ianstormtaylor/superstruct/blob/main/src/utils.ts) and the most relevant code appears to be `ObjectType` and `Optionalize`. If you have any suggestions on what might be happening, I could try and dig deeper. Or if you have a solution, even better. :smiley:

**Comment by thesunny** [comment] 2022-04-25 21:57
So the solution here is to have `strictNullChecks` set to `true`.

I think it's important to note in the documentation superstruct will NOT work with the default tsconfig. You must enable `strictNullChecks`. For clarity, if you enable `strict` mode, that will also enable `strictNullChecks`.

In my particular issue, I had an inheritance issue between various `tsconfig` files so if you are having an issue, that's something you might want to check.

**Comment by thesunny** [comment] 2022-06-02 23:23
Hi @ianstormtaylor 

My comment was ambiguous so to clarify...

I mean to suggest to add to the documentation that SuperStruct won't work specifically with the default tsconfig. In other words, one must manually enable the option as a step on a new project. Because a lot of presets enable `strictNullChecks` or `strict` mode (which also enables `strictNullChecks`) it can be easy to forget that `strict` mode is not on by default.

Any chance to give me contributor access to this project? I know I can do a PR but I find I contribute more often when I can just pull and push.

**Comment by ianstormtaylor** [comment] 2022-06-03 08:11
@thesunny absolutely! Just added you as a contributor, thanks for the help! I think we're on the same page, but this is the part from the [Using TypeScript]() guide I was thinking about:

> 🤖 Warning: If you are not using TypeScript's [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) option, Superstruct will be unable to infer your "optional" types correctly and will mark all types as optional.

Which maybe we can rephrase a little stronger:

> 🤖 Warning: You must enable TypeScript's [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) option for Superstruct to work properly with "optional" types.

I figure we can add that to the [`optional` Reference](https://docs.superstructjs.org/api-reference/types#optional) and the [TypeScript Reference](https://docs.superstructjs.org/api-reference/typescript) as well and that should cover the three places where people would be looking when they run into this problem.

**Comment by thesunny** [comment] 2022-06-04 01:06
Hi @ianstormtaylor 

I like that wording. I added a few details. Here's what I ended up with which I updated and also added to the `optional` section of `reference/types.md`:

> 🤖 Warning: You must enable TypeScript's [`strictNullChecks`](https://www.typescriptlang.org/tsconfig#strictNullChecks) option in your `tsconfig.json` for Superstruct to work properly with "optional" types. Note that `strictNullChecks` is disabled by default. If you enable `strict`, `strictNullChecks` will automatically be enabled.

I think that's clear enough. I'm closing this issue.

**Closed by thesunny** 2022-06-04 01:06 UTC
Labels: docs, ♥ help please
