### ISSUE TITLE
Usage for other than types validations

### ISSUE THREAD

**Issue by VladShcherbin** [ianstormtaylor/superstruct#47] opened 2017-12-08 07:07 UTC
Hey

I checked the docs, but didn't find any info if this library is supposed to be used only to validate **types** of data or it can be used for other validations.

For example, I can check if value is a number. Is it possible and how to check, if this value is less than 100 or more than 6?

**Comment by poltib** [comment] 2017-12-08 10:23
You [custom types](https://github.com/ianstormtaylor/superstruct/blob/master/docs/reference.md#custom-types) for that.

**Comment by VladShcherbin** [comment] 2017-12-08 10:29
@poltib yep, I saw this in the docs, how will you create dynamic type where you can pass arguments? For example for length rule and its value 100 or other.

**Comment by ianstormtaylor** [comment] 2017-12-08 17:40
Hey @VladShcherbin good question, can you explain your use case for the length check? Thanks!

**Comment by VladShcherbin** [comment] 2017-12-08 18:25
@ianstormtaylor I was interested in using this library as a validation library, here are some of typical type checks I'll need (with ref links about what they do):

- [min](https://laravel.com/docs/5.5/validation#rule-min) - to check min value
- [max](https://laravel.com/docs/5.5/validation#rule-max) - to check max value
- [between](https://laravel.com/docs/5.5/validation#rule-between) - to check if value is between min and max value
- [before](https://laravel.com/docs/5.5/validation#rule-before) - to check date
- other dynamic types where you need to pass arguments

**Comment by VladShcherbin** [comment] 2017-12-08 18:39
There are similar rules (or type checks) in libraries from the docs:

- joi: [min](https://github.com/hapijs/joi/blob/v13.0.2/API.md#stringminlimit-encoding), [max](https://github.com/hapijs/joi/blob/v13.0.2/API.md#stringmaxlimit-encoding)
- validator.js: [isLength](https://github.com/chriso/validator.js#validators)
- yup: [min](https://github.com/jquense/yup#stringminlimit-number--ref-message-string-schema), [max](https://github.com/jquense/yup#stringmaxlimit-number--ref-message-string-schema)
- ajv: [maxLength / minLengthT](https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#keywords-for-strings)

**Comment by ianstormtaylor** [comment] 2017-12-10 06:55
@VladShcherbin what specific types of data are you looking to use min/max length checks for? This library is built differently than Joi/etc. and encourages different patterns. But I'm curious to hear what your use case needs them for before I write up an explanation assuming things.

**Comment by VladShcherbin** [comment] 2017-12-10 07:06
@ianstormtaylor I'd like to start at least with basic ones, strings and numbers - min/max/between for them.

**Comment by VladShcherbin** [comment] 2017-12-10 07:09
Another rule I use everywhere is `unique` where I can pass the database table name and column so I can use them to check value dynamically. Something like this: `unique('articles', 'title')`. I'm interested in this one too.

**Comment by ianstormtaylor** [comment] 2017-12-10 07:32
@VladShcherbin so I think the issue is that Superstruct encourages doing things a little differently. With other validation libraries (eg. Joi) you'll often define "types" inline, by doing things like:

```js
username: Joi.string().alphanum().min(3).max(30).required()
```

Superstruct doesn't do this, by design. Instead it encourages you to define you data types upfront, in one place, and then refer to them elsewhere. So instead of defining the specific birthdate validation inline, you do something like:

```js
const struct = superstruct({
  types: {
    username: v => typeof v === 'string' && v.length > 3 && v.length < 30 && /[a-zA-Z0-9]+/.test(v)
  }
})

const User = struct({
  id: 'number',
  name: 'string',
  username: 'username',
  ...
})
```

This way you have a single source of truth for data types, and can re-use them across objects. For example, you might call that data type `login` instead, and use it not just for users, but for many different objects in your database. I've found this to be a lot cleaner, and lead to easier to maintain code. (Of course, if you don't like this decision, the other validation libraries might be better for you.)

---

If this is really not something you want, and you want to define things inline (which can be valid for certain use cases that have to be dynamic), you can have validation functions right in the struct definition, for example:

```js
const User = struct({
  id: 'number',
  name: 'string',
  username: v => typeof v === 'string' && v.length > 3 && v.length < 30 && /[a-zA-Z0-9]+/.test(v),
  ...
})
```

That way you can get custom without having to define the type up front.

---

As for the `unique` database constraint, I wouldn't conflate that with validation, and would just let that fail at the database level personally. But check out #48 for the reason why Superstruct doesn't support async validations.

---

Hope that helps! I'm going to close this out as a question, but feel free to ask follow ups here if you have any other questions about this.

**Closed by ianstormtaylor** 2017-12-10 07:32 UTC
Labels: question

**Comment by VladShcherbin** [comment] 2017-12-10 07:45
@ianstormtaylor thank you for such a detailed answer, resolved all questions I have :)

**Comment by christhomas** [comment] 2019-06-04 18:45
This is absolutely awful. You wrote a data validator which can't even do the most basic validations and to do them, I have to write practically the entire validation myself, and add on the extra things myself.

What on earth are you thinking? This lack of basic functionality makes this library worthless :/ If I have to write basic validations myself, then there is absolutely no benefit to using this library since practically EVERY REAL WORLD USE, would require this basic, yet missing feature. 2 years later.....

**Comment by frandiox** [comment] 2019-12-06 05:36
@ianstormtaylor In love with Superstruct, but struggling a bit with this. How would you go about returning proper errors with this kind of validation? Something like "Value exceeds 80 characters". If we use a function that just returns `false` when any of the internal checks fail, then I don't know how create an error message.

**Comment by ianstormtaylor** [comment] 2019-12-06 15:42
@frandiox good question, that part isn't super well documented, but if you're specifically looking to attach more information to your errors you can return failure object from the validators, not just booleans. But booleans are the 90% case.

Check out the [`Validator`](https://www.superstructjs.org/globals.html#validator) reference, which for now is the best place to see it. It's those `Failure` objects that can be returned.
