### ISSUE TITLE
Can't run tests or build

### ISSUE THREAD

**Issue by aphofstede** [ianstormtaylor/superstruct#203] opened 2019-12-09 16:25 UTC
I tried to run the tests locally but there appears to be a problem:
```
PS [...]\src\superstruct> yarn test
yarn run v1.19.2
$ yarn test:types && yarn test:mocha
$ yarn build:types && tsc --noEmit && tsc --project ./test/tsconfig.json --noEmit
$ tsc --emitDeclarationOnly --declarationMap --outDir ./lib
$ yarn build:cjs && mocha --require ./test/register --require source-map-support/register ./test/index.ts
$ rollup --config ./config/rollup-cjs.js

./src/index.ts → ./lib/index.js...
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
(!) Circular dependency: src\superstruct.ts -> src\structs\index.ts -> src\structs\shorthand.ts -> src\index.ts -> src\superstruct.ts
created ./lib/index.js in 3.1s
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`

../src/index.ts:12
const struct = superstruct()
               ^
TypeError: superstruct is not a function
    at Object.<anonymous> (../src/index.ts:12:16)
    at Module._compile (module.js:652:30)
    at Module._compile ([...]src\superstruct\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] ([...]src\superstruct\node_modules\pirates\lib\index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> ([...]src\superstruct\test\fixtures\array-objects/defaults.ts:1:1)
    at Module._compile (module.js:652:30)
    at Module._compile ([...]src\superstruct\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .ts] ([...]src\superstruct\node_modules\pirates\lib\index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at _loop2 ([...]src\superstruct\test/index.ts:22:24)
    at Suite.<anonymous> ([...]src\superstruct\test/index.ts:21:33)
    at Object.create ([...]src\superstruct\node_modules\mocha\lib\interfaces\common.js:140:19)
    at describe ([...]src\superstruct\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at _loop ([...]src\superstruct\test/index.ts:14:5)
    at Suite.<anonymous> ([...]src\superstruct\test/index.ts:13:29)
    at Object.create ([...]src\superstruct\node_modules\mocha\lib\interfaces\common.js:140:19)
    at describe ([...]src\superstruct\node_modules\mocha\lib\interfaces\bdd.js:42:27)
    at Object.<anonymous> ([...]src\superstruct\test/index.ts:6:1)
    at Module._compile (module.js:652:30)
    at Module._compile ([...]src\superstruct\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .ts] ([...]src\superstruct\node_modules\pirates\lib\index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at [...]src\superstruct\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles ([...]src\superstruct\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run ([...]src\superstruct\node_modules\mocha\lib\mocha.js:809:10)
    at Object.exports.singleRun ([...]src\superstruct\node_modules\mocha\lib\cli\run-helpers.js:108:16)
    at exports.runMocha ([...]src\superstruct\node_modules\mocha\lib\cli\run-helpers.js:142:13)
    at Object.exports.handler.argv [as handler] ([...]src\superstruct\node_modules\mocha\lib\cli\run.js:292:3)
    at Object.runCommand ([...]src\superstruct\node_modules\yargs\lib\command.js:242:26)
    at Object.parseArgs [as _parseArgs] ([...]src\superstruct\node_modules\yargs\yargs.js:1087:28)
    at Object.parse ([...]src\superstruct\node_modules\yargs\yargs.js:566:25)
    at Object.exports.main ([...]src\superstruct\node_modules\mocha\lib\cli\cli.js:68:6)
    at Object.<anonymous> ([...]src\superstruct\node_modules\mocha\bin\mocha:164:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

yarn build also appears to have some problems:
```
  $ typedoc ./src/index.ts ./src/@types/*.ts && cp -f ./site/globals.html ./site/index.html
  fs.js:948
    binding.stat(pathModule._makeLong(path));
            ^
  
  Error: ENOENT: no such file or directory, stat '[...]\src\superstruct\src\@types\*.ts'
      at Object.fs.statSync (fs.js:948:11)
      at add ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\application.js:111:34)
      at inputFiles.forEach.file ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\application.js:128:13)
      at Array.forEach (<anonymous>)
      at CliApplication.expandInputFiles ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\application.js:127:20)
      at CliApplication.bootstrap ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\cli.js:39:30)
      at new Application ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\application.js:31:14)
      at new CliApplication ([...]\src\superstruct\node_modules\@gnd\typedoc\dist\lib\cli.js:22:1)
      at Object.<anonymous> ([...]\src\superstruct\node_modules\@gnd\typedoc\bin\typedoc:4:1)
      at Module._compile (module.js:652:30)
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ianstormtaylor** [comment] 2019-12-09 18:03
Hmm that's weird, I can't reproduce exactly.

What `node` and `yarn` version?

**Comment by aphofstede** [comment] 2019-12-10 09:33
yarn run v1.19.2
node was on 8.10.. I'll try with a newer version

**Comment by aphofstede** [comment] 2019-12-10 10:25
Same with 12.13.0

**Comment by aphofstede** [comment] 2019-12-10 10:28
Perhaps the circular dependency is to blame?

**Comment by ianstormtaylor** [comment] 2019-12-16 19:18
Did you run `yarn install` first?

**Comment by aphofstede** [comment] 2019-12-19 16:20
Yes

**Comment by ianstormtaylor** [comment] 2019-12-19 16:57
I can't reproduce this locally with:

```
yarn 1.19.1
node 12.14.0
```

**Comment by ianstormtaylor** [comment] 2019-12-19 19:39
Should be fixed in latest release!

**Closed by ianstormtaylor** 2019-12-19 19:39 UTC

**Comment by unixnut** [comment] 2022-10-24 15:02
Looks like a regression in v0.16.5:
`const superstruct_1 = require("superstruct");
const struct = superstruct_1.superstruct({`

> TypeError: superstruct_1.superstruct is not a function
>    at Object.<anonymous> (/srv/web/outline_agencies/node_modules/@relative-ci/agent/node_modules/@bundle-stats/plugin-webpack-validate/lib/schemas.js:5:30
> ...
